"""
Dictionary mapping moods to lists of YouTube search keywords.
"""

 
mood_keywords = {
    "joy": [
    "Happy — Pharrell Williams",
    "Uptown Funk — Mark Ronson ft. Bruno Mars",
    "Dancing Queen — ABBA",
    "Walking on Sunshine — Katrina & the Waves",
    "Don't Stop Me Now — Queen",
    "Shake It Off — Taylor Swift",
    "Can't Stop the Feeling — Justin Timberlake",
    "Good as Hell — Lizzo",
    "Sugar — Maroon 5",
    "Best Day of My Life — American Authors",
    "I Got a Feeling — The Black Eyed Peas",
    "Valerie — Mark Ronson ft. Amy Winehouse",
    "On Top of the World — Imagine Dragons",
    "Firework — Katy Perry",
    "September — Earth, Wind & Fire",
    "I'm Still Standing — Elton John",
    "High Hopes — Panic! At The Disco",
    "Wake Me Up — Avicii",
    "Good Time — Owl City & Carly Rae Jepsen",
    "Counting Stars — OneRepublic",
    "Feel It Still — Portugal. The Man",
    "Levitating — Dua Lipa ft. DaBaby",
    "Shotgun — George Ezra",
    "Rather Be — Clean Bandit ft. Jess Glynne",
    "Stronger (What Doesn’t Kill You) — Kelly Clarkson",
    "Roar — Katy Perry",
    "Blinding Lights — The Weeknd",
    "What Makes You Beautiful — One Direction",
    "Pompeii — Bastille",
    "Shut Up and Dance — WALK THE MOON",
    "Tik Tok — Kesha",
    "Best Song Ever — One Direction",
    "Love on Top — Beyoncé",
    "Ain’t No Mountain High Enough — Marvin Gaye & Tammi Terrell",
    "Dancing in the Moonlight — Toploader",
    "Treasure — Bruno Mars",
    "Stereo Hearts — Gym Class Heroes ft. Adam Levine",
    "You Make My Dreams — Hall & Oates",
    "Good Morning — Kanye West",
    "I'm a Believer — Smash Mouth",
    "Banana Pancakes — Jack Johnson",
    "Smile — Uncle Kracker",
    "Classic — MKTO",
    "Life is a Highway — Rascal Flatts",
    "Safe and Sound — Capital Cities",
    "Just the Way You Are — Bruno Mars",
    "Say Hey (I Love You) — Michael Franti & Spearhead",
    "Send Me On My Way — Rusted Root",
    "Mr. Blue Sky — Electric Light Orchestra",
    "Brown Eyed Girl — Van Morrison",
    "Dog Days Are Over — Florence + The Machine",
    "Lucky — Jason Mraz ft. Colbie Caillat",
    "Pocketful of Sunshine — Natasha Bedingfield",
    "Electric Love — Børns",
    "Beautiful Day — U2",
    "Soulmate — Lizzo",
    "My Type — Saint Motel",
    "Adventure of a Lifetime — Coldplay",
    "Love Me Like You Do — Ellie Goulding",
    "Sunflower — Post Malone & Swae Lee",
    "24K Magic — Bruno Mars",
    "Beautiful Girls — Sean Kingston",
    "Good Day — Nappy Roots",
    "It’s My Life — Bon Jovi",
    "We Found Love — Rihanna ft. Calvin Harris",
    "I Wanna Dance With Somebody — Whitney Houston",
    "Everything — Michael Bublé",
    "Burn — Ellie Goulding",
    "Summer — Calvin Harris",
    "One Kiss — Calvin Harris & Dua Lipa",
    "Cake by the Ocean — DNCE",
    "Cheerleader — OMI",
    "The Lazy Song — Bruno Mars",
    "Paradise — Coldplay",
    "Magic — B.o.B ft. Rivers Cuomo",
    "Bright — Echosmith",
    "Riptide — Vance Joy",
    "Lush Life — Zara Larsson",
    "Geronimo — Sheppard",
    "Sugar, We're Goin Down — Fall Out Boy",
    "Come On Eileen — Dexys Midnight Runners",
    "HandClap — Fitz and The Tantrums",
    "Super Trouper — ABBA",
    "Let’s Go Crazy — Prince",
    "Born to Run — Bruce Springsteen",
    "You Are the Best Thing — Ray LaMontagne",
    "Jump — Van Halen",
    "We Are Young — fun. ft. Janelle Monáe",
    "No Roots — Alice Merton",
    "The Middle — Zedd, Maren Morris, Grey",
    "Happy Now — Kygo ft. Sandro Cavazza",
    "Take on Me — a-ha",
    "Can’t Hold Us — Macklemore & Ryan Lewis",
    "Boom Clap — Charli XCX",
    "Don't Start Now — Dua Lipa",
    "Feel Good Inc. — Gorillaz",
    "Put Your Records On — Corinne Bailey Rae",
    "Freedom! '90 — George Michael",
    "Good Feeling — Flo Rida",
    "Tongue Tied — Grouplove",
    "Love Never Felt So Good — Michael Jackson & Justin Timberlake"
],
    "sadness": [
    "Someone Like You — Adele",
    "Let Her Go — Passenger",
    "Fix You — Coldplay",
    "Hurt — Johnny Cash",
    "Tears in Heaven — Eric Clapton",
    "The Night We Met — Lord Huron",
    "Skinny Love — Bon Iver",
    "Fast Car — Tracy Chapman",
    "Creep — Radiohead",
    "Nothing Compares 2 U — Sinéad O'Connor",
    "All I Want — Kodaline",
    "I Will Always Love You — Whitney Houston",
    "Say Something — A Great Big World & Christina Aguilera",
    "The A Team — Ed Sheeran",
    "Breathe Me — Sia",
    "Lost Boy — Ruth B",
    "When I Was Your Man — Bruno Mars",
    "Back to Black — Amy Winehouse",
    "Liability — Lorde",
    "Jealous — Labrinth",
    "Let It Go — James Bay",
    "Youth — Daughter",
    "Shadow of the Day — Linkin Park",
    "Un-break My Heart — Toni Braxton",
    "I’ll Never Love Again — Lady Gaga",
    "From the Dining Table — Harry Styles",
    "I Found — Amber Run",
    "All Too Well (10 Minute Version) — Taylor Swift",
    "Everybody Hurts — R.E.M.",
    "Concrete Angel — Martina McBride",
    "The Scientist — Coldplay",
    "Lost — Michael Bublé",
    "In the Arms of an Angel — Sarah McLachlan",
    "Forever — Lewis Capaldi",
    "The Sound of Silence — Simon & Garfunkel",
    "Happier — Ed Sheeran",
    "Say You Love Me — Jessie Ware",
    "Always Remember Us This Way — Lady Gaga",
    "She Used To Be Mine — Sara Bareilles",
    "Let Me Down Slowly — Alec Benjamin",
    "Dancing On My Own — Robyn",
    "Run — Snow Patrol",
    "I Can’t Make You Love Me — Bonnie Raitt",
    "My Immortal — Evanescence",
    "Half A Man — Dean Lewis",
    "Arcade — Duncan Laurence",
    "Somebody Else — The 1975",
    "Drivers License — Olivia Rodrigo",
    "Exile — Taylor Swift ft. Bon Iver",
    "Falling — Harry Styles",
    "Visions of Gideon — Sufjan Stevens",
    "Supermarket Flowers — Ed Sheeran",
    "Almost Lover — A Fine Frenzy",
    "Let Me In — Grouplove",
    "Say You Won’t Let Go — James Arthur",
    "Older — Sasha Alex Sloan",
    "Too Good at Goodbyes — Sam Smith",
    "Candle In The Wind — Elton John",
    "Pieces — Red",
    "Jar of Hearts — Christina Perri",
    "The One That Got Away — Katy Perry",
    "Lost Without You — Freya Ridings",
    "Bruises — Lewis Capaldi",
    "If I Die Young — The Band Perry",
    "Let You Break My Heart Again — Laufey",
    "This Woman’s Work — Kate Bush",
    "Youth — Troye Sivan",
    "The Blower’s Daughter — Damien Rice",
    "Wrecking Ball — Miley Cyrus",
    "Goodbye My Lover — James Blunt",
    "Fix a Heart — Demi Lovato",
    "I’m Not The Only One — Sam Smith",
    "Just Give Me a Reason — Pink ft. Nate Ruess",
    "Wish You Were Here — Pink Floyd",
    "The Book of Love — Peter Gabriel",
    "Leave Right Now — Will Young",
    "Try — Colbie Caillat",
    "Heavy — Linkin Park ft. Kiiara",
    "Shallow — Lady Gaga & Bradley Cooper",
    "Skin — Rag’n’Bone Man",
    "Foolish Games — Jewel",
    "Love In The Dark — Adele",
    "We Don't Talk Anymore — Charlie Puth ft. Selena Gomez",
    "Small Bump — Ed Sheeran",
    "Only Love Can Hurt Like This — Paloma Faith",
    "Tolerate It — Taylor Swift",
    "Not About Angels — Birdy",
    "Talking to the Moon — Bruno Mars",
    "Breakeven — The Script",
    "You Were Good to Me — Jeremy Zucker & Chelsea Cutler",
    "Gone — NF",
    "I Know I’m Not the Only One — Sam Smith",
    "Scars To Your Beautiful — Alessia Cara",
    "Where’s My Love — SYML",
    "Graceland Too — Phoebe Bridgers",
    "This Town — Niall Horan",
    "Love is a Losing Game — Amy Winehouse",
    "Unsteady — X Ambassadors",
    "Angel — Jimi Hendrix",
    "Echo — Jason Walker",
    "All of Me (Sad Version) — John Legend",
    "Train Wreck — James Arthur",
    "Chasing Cars — Snow Patrol"
],
    "anger": [
    "Smells Like Teen Spirit — Nirvana",
    "Killing In The Name — Rage Against The Machine",
    "Master of Puppets — Metallica",
    "Break Stuff — Limp Bizkit",
    "Before I Forget — Slipknot",
    "Stronger — Kanye West",
    "You Oughta Know — Alanis Morissette",
    "In The End — Linkin Park",
    "Bodies — Drowning Pool",
    "Given Up — Linkin Park",
    "Chop Suey! — System of a Down",
    "Duality — Slipknot",
    "One Step Closer — Linkin Park",
    "Enter Sandman — Metallica",
    "People = Sh*t — Slipknot",
    "Headstrong — Trapt",
    "The Way I Am — Eminem",
    "Down with the Sickness — Disturbed",
    "Bleed It Out — Linkin Park",
    "Faint — Linkin Park",
    "All My Life — Foo Fighters",
    "Papercut — Linkin Park",
    "Walk — Pantera",
    "Dig — Mudvayne",
    "American Idiot — Green Day",
    "My Own Summer (Shove It) — Deftones",
    "Animal I Have Become — Three Days Grace",
    "Pain — Three Days Grace",
    "I Hate Everything About You — Three Days Grace",
    "Indestructible — Disturbed",
    "Bulls on Parade — Rage Against The Machine",
    "Psychosocial — Slipknot",
    "Fuel — Metallica",
    "Given to Fly — Pearl Jam",
    "Battery — Metallica",
    "Fight The Power — Public Enemy",
    "Freak on a Leash — Korn",
    "Riot — Three Days Grace",
    "Sabotage — Beastie Boys",
    "All the Small Things — blink-182",
    "Jeremy — Pearl Jam",
    "The Kill (Bury Me) — 30 Seconds to Mars",
    "Lying From You — Linkin Park",
    "My Hero — Foo Fighters",
    "Numb — Linkin Park",
    "Boom — P.O.D.",
    "Revolution — The Score",
    "Know Your Enemy — Green Day",
    "B.Y.O.B. — System of a Down",
    "Uprising — Muse",
    "House of Wolves — Bring Me the Horizon",
    "Throne — Bring Me the Horizon",
    "I Will Not Bow — Breaking Benjamin",
    "Dance with the Devil — Breaking Benjamin",
    "Diary of Jane — Breaking Benjamin",
    "No One Knows — Queens of the Stone Age",
    "Stressed Out — Twenty One Pilots",
    "Heathens — Twenty One Pilots",
    "DNA — Kendrick Lamar",
    "Black Skinhead — Kanye West",
    "Monster — Kanye West ft. Jay-Z, Rick Ross, Nicki Minaj, Bon Iver",
    "Sicko Mode — Travis Scott",
    "Venom — Eminem",
    "Till I Collapse — Eminem ft. Nate Dogg",
    "Rap God — Eminem",
    "Pray for Me — The Weeknd & Kendrick Lamar",
    "Lose Yourself — Eminem",
    "Man That You Fear — Marilyn Manson",
    "This Is War — Thirty Seconds to Mars",
    "Painkiller — Judas Priest",
    "Runnin’ — 21 Savage & Metro Boomin",
    "Blood // Water — grandson",
    "I Think I'm Okay — Machine Gun Kelly ft. Yungblud & Travis Barker",
    "Toxicity — System of a Down",
    "Wait and Bleed — Slipknot",
    "World So Cold — Mudvayne",
    "Warriors — Imagine Dragons",
    "Radioactive — Imagine Dragons",
    "Believer — Imagine Dragons",
    "No Shelter — Rage Against The Machine",
    "Not Afraid — Eminem",
    "Welcome to the Black Parade — My Chemical Romance",
    "Helena — My Chemical Romance",
    "Misery Business — Paramore",
    "Decode — Paramore",
    "Crushcrushcrush — Paramore",
    "The Pretender — Foo Fighters",
    "Run — Foo Fighters",
    "Pain Remains — Lorna Shore",
    "Bite Back — Wage War",
    "Mantra — Bring Me the Horizon",
    "I Don’t Like the Drugs (But the Drugs Like Me) — Marilyn Manson",
    "Crawling — Linkin Park",
    "We Are — Hollywood Undead",
    "Undead — Hollywood Undead",
    "Enemies — Shinedown",
    "Devour — Shinedown",
    "Animal — Neon Trees",
    "No More Sorrow — Linkin Park",
    "Re-Education (Through Labor) — Rise Against",
    "Prayer of the Refugee — Rise Against",
    "Give It Away — Red Hot Chili Peppers"
],
    "fear": [
    "Weightless — Marconi Union",
    "Breathe Me — Sia",
    "Holocene — Bon Iver",
    "Sound of Silence — Simon & Garfunkel",
    "Mad World — Gary Jules",
    "River Flows in You — Yiruma",
    "No Surprises — Radiohead",
    "Everybody’s Got to Learn Sometime — Beck",
    "Black — Pearl Jam",
    "Lost — Michael Bublé",
    "Videotape — Radiohead",
    "Hurt — Nine Inch Nails",
    "Intro — The xx",
    "Experience — Ludovico Einaudi",
    "Motion Picture Soundtrack — Radiohead",
    "Welcome to the Black Parade (Intro) — My Chemical Romance",
    "Gorecki — Lamb",
    "Teardrop — Massive Attack",
    "Angel — Massive Attack",
    "Nightmare — Halsey",
    "Dark Paradise — Lana Del Rey",
    "Born to Die — Lana Del Rey",
    "Pyramid Song — Radiohead",
    "Snuff — Slipknot",
    "Lux Aeterna — Clint Mansell",
    "Requiem for a Dream — Clint Mansell",
    "Elegy — Lisa Gerrard & Patrick Cassidy",
    "Disintegration Anxiety — Explosions in the Sky",
    "We Found Each Other in the Dark — City and Colour",
    "The Host of Seraphim — Dead Can Dance",
    "Mountains — Hans Zimmer",
    "Time — Hans Zimmer",
    "Spiegel im Spiegel — Arvo Pärt",
    "Arrival of the Birds — The Cinematic Orchestra",
    "All the Good Girls Go to Hell — Billie Eilish",
    "bury a friend — Billie Eilish",
    "Everything I Wanted — Billie Eilish",
    "Oats in the Water — Ben Howard",
    "I Know Places — Taylor Swift",
    "Fire Meet Gasoline — Sia",
    "The Haunting — Anomie Belle",
    "Eyes on Fire — Blue Foundation",
    "Flickers — Son Lux",
    "Formidable — Stromae",
    "4AM — Our Lady Peace",
    "How to Disappear — Lana Del Rey",
    "Open — Rhye",
    "Unravel — Björk",
    "Into Dust — Mazzy Star",
    "Save Me — Aimee Mann",
    "Waiting Game — BANKS",
    "Undertow — Warpaint",
    "Bleeding Out — Imagine Dragons",
    "Demons — Imagine Dragons",
    "Fear — OneRepublic",
    "I Am Not a Robot — MARINA",
    "Haunted — Beyoncé",
    "Control — Halsey",
    "Oblivion — Bastille",
    "The Wolves (Act I and II) — Bon Iver",
    "Bloodflood — alt-J",
    "Interlude: Shadow — BTS",
    "Unsteady — X Ambassadors",
    "Youth — Daughter",
    "Smother — Daughter",
    "To Build a Home — The Cinematic Orchestra",
    "Heartbeats — José González",
    "Weather Storm — Craig Armstrong",
    "This Place is a Prison — The Postal Service",
    "St. Jude — Florence + The Machine",
    "Shake Me Down — Cage the Elephant",
    "Winter — Joshua Radin",
    "Storms — Fleetwood Mac",
    "Pet Sematary — The Ramones",
    "Twilight — Elliot Smith",
    "Colorblind — Counting Crows",
    "Laura Palmer — Bastille",
    "The Fear — Ben Howard",
    "No Light, No Light — Florence + The Machine",
    "Lullaby — Sia",
    "The End — The Doors",
    "Possibility — Lykke Li",
    "The Killing Moon — Echo & The Bunnymen",
    "Where Did You Sleep Last Night — Nirvana",
    "Something in the Way — Nirvana",
    "I Am Stretched On Your Grave — Sinéad O'Connor",
    "Leave Me — Alex G",
    "Tether — CHVRCHES",
    "Ill Wind — Radiohead",
    "Clair de Lune — Debussy",
    "Nara — alt-J",
    "Dead in the Water — Ellie Goulding",
    "Fear and Loathing — Marina and the Diamonds",
    "Hide and Seek — Imogen Heap",
    "Darkness — Darren Hayes",
    "Wake Me — Bleachers",
    "Cold — Aqualung & Lucy Schwartz",
    "The Night — Valerie Broussard",
    "I Went Too Far — AURORA",
    "Runaway — AURORA",
    "Nightcall — Kavinsky",
    "Don’t Let Me Be Misunderstood — Nina Simone",
    "Theme from Schindler’s List — John Williams",
    "Ghost Story — Sting",
    "The Fear — Lily Allen"
],
    "surprise": [
    "Bohemian Rhapsody — Queen",
    "Take On Me — A-ha",
    "Feel Good Inc. — Gorillaz",
    "Electric Feel — MGMT",
    "Some Nights — fun.",
    "Dog Days Are Over — Florence + The Machine",
    "Royals — Lorde",
    "Clint Eastwood — Gorillaz",
    "Pumped Up Kicks — Foster the People",
    "Mr. Brightside — The Killers",
    "Kids — MGMT",
    "Little Talks — Of Monsters and Men",
    "Somebody That I Used to Know — Gotye ft. Kimbra",
    "Riptide — Vance Joy",
    "Take Me Out — Franz Ferdinand",
    "1901 — Phoenix",
    "Tongue Tied — Grouplove",
    "Come On Eileen — Dexys Midnight Runners",
    "Midnight City — M83",
    "I Bet You Look Good on the Dancefloor — Arctic Monkeys",
    "We Are Young — fun. ft. Janelle Monáe",
    "Left Hand Free — alt-J",
    "Reptilia — The Strokes",
    "Lisztomania — Phoenix",
    "No One Knows — Queens of the Stone Age",
    "A-Punk — Vampire Weekend",
    "Helena Beat — Foster the People",
    "Breezeblocks — alt-J",
    "Radioactive — Imagine Dragons",
    "Weird Fishes/Arpeggi — Radiohead",
    "Hide and Seek — Imogen Heap",
    "Taro — alt-J",
    "MoneyGrabber — Fitz and The Tantrums",
    "Golden Brown — The Stranglers",
    "Icky Thump — The White Stripes",
    "Unbelievable — EMF",
    "Rock Lobster — The B-52's",
    "My Girls — Animal Collective",
    "We Used to Wait — Arcade Fire",
    "Get Lucky — Daft Punk ft. Pharrell Williams",
    "Feel It Still — Portugal. The Man",
    "Bang Bang — Nancy Sinatra",
    "Do I Wanna Know? — Arctic Monkeys",
    "Technologic — Daft Punk",
    "Frontier Psychiatrist — The Avalanches",
    "No Roots — Alice Merton",
    "Out of My League — Fitz and The Tantrums",
    "Take a Walk — Passion Pit",
    "Electric Love — Børns",
    "Dance Yrself Clean — LCD Soundsystem",
    "Go! — The Chemical Brothers ft. Q-Tip",
    "We Come Running — Youngblood Hawke",
    "Mountain Sound — Of Monsters and Men",
    "Tightrope — Janelle Monáe ft. Big Boi",
    "Coffee — Sylvan Esso",
    "Houdini — Foster the People",
    "Golden Skans — Klaxons",
    "Sprawl II (Mountains Beyond Mountains) — Arcade Fire",
    "You! Me! Dancing! — Los Campesinos!",
    "Cape Cod Kwassa Kwassa — Vampire Weekend",
    "Peach — Broods",
    "Alaska — Maggie Rogers",
    "Space Song — Beach House",
    "Let’s Dance — David Bowie",
    "Heroes — David Bowie",
    "This Must Be the Place (Naive Melody) — Talking Heads",
    "Psycho Killer — Talking Heads",
    "Once in a Lifetime — Talking Heads",
    "Elephant — Tame Impala",
    "Let It Happen — Tame Impala",
    "New Person, Same Old Mistakes — Tame Impala",
    "Harmony Hall — Vampire Weekend",
    "Electric Avenue — Eddy Grant",
    "Blister in the Sun — Violent Femmes",
    "Groove is in the Heart — Deee-Lite",
    "Genesis — Grimes",
    "Kill V. Maim — Grimes",
    "Crave You — Flight Facilities ft. Giselle",
    "Infinity — Jaymes Young",
    "Light & Day — The Polyphonic Spree",
    "Such Great Heights — The Postal Service",
    "123456 — Fitz and The Tantrums",
    "Somebody’s Watching Me — Rockwell",
    "Na Na Na — My Chemical Romance",
    "Sleepyhead — Passion Pit",
    "Electric Avenue — Eddy Grant",
    "Don’t Come Around Here No More — Tom Petty & The Heartbreakers",
    "Revolution 909 — Daft Punk",
    "The Less I Know The Better — Tame Impala",
    "Digital Love — Daft Punk",
    "Howlin’ For You — The Black Keys",
    "Tennis Court — Lorde",
    "Paris — Magic Man",
    "Black Mambo — Glass Animals",
    "Gooey — Glass Animals",
    "Deadcrush — alt-J",
    "Doom Days — Bastille",
    "Style — Taylor Swift",
    "Midnight — Coldplay",
    "Motion Sickness — Phoebe Bridgers",
    "New Magic Wand — Tyler, The Creator",
    "IGOR’S THEME — Tyler, The Creator",
    "Two Weeks — FKA twigs",
    "Cellophane — FKA twigs"
],
    "love": [
    "I Will Always Love You — Whitney Houston",
    "My Heart Will Go On — Celine Dion",
    "Thinking Out Loud — Ed Sheeran",
    "Perfect — Ed Sheeran",
    "All of Me — John Legend",
    "Just the Way You Are — Bruno Mars",
    "Your Song — Elton John",
    "Make You Feel My Love — Adele",
    "Wonderful Tonight — Eric Clapton",
    "A Thousand Years — Christina Perri",
    "At Last — Etta James",
    "Can’t Help Falling in Love — Elvis Presley",
    "Unchained Melody — The Righteous Brothers",
    "Endless Love — Diana Ross & Lionel Richie",
    "Because You Loved Me — Celine Dion",
    "Everything — Michael Bublé",
    "You Are the Reason — Calum Scott",
    "I Don’t Want to Miss a Thing — Aerosmith",
    "I’m Yours — Jason Mraz",
    "Marry Me — Train",
    "Truly Madly Deeply — Savage Garden",
    "Let’s Stay Together — Al Green",
    "Bleeding Love — Leona Lewis",
    "Back at One — Brian McKnight",
    "Love Me Like You Do — Ellie Goulding",
    "Something — The Beatles",
    "Yellow — Coldplay",
    "The Way You Look Tonight — Frank Sinatra",
    "When a Man Loves a Woman — Percy Sledge",
    "Just Give Me a Reason — P!nk ft. Nate Ruess",
    "Always — Bon Jovi",
    "No One — Alicia Keys",
    "How Deep Is Your Love — Bee Gees",
    "You’re Still the One — Shania Twain",
    "If I Ain’t Got You — Alicia Keys",
    "Stand by Me — Ben E. King",
    "Let Her Go — Passenger",
    "From This Moment On — Shania Twain",
    "All My Life — K-Ci & JoJo",
    "I Won’t Give Up — Jason Mraz",
    "Say You Won’t Let Go — James Arthur",
    "You and I — One Direction",
    "Love on the Brain — Rihanna",
    "Halo — Beyoncé",
    "Adore You — Harry Styles",
    "Collide — Howie Day",
    "Love Story — Taylor Swift",
    "Lover — Taylor Swift",
    "Truly — Lionel Richie",
    "Can’t Take My Eyes Off You — Frankie Valli",
    "Still Into You — Paramore",
    "Shallow — Lady Gaga & Bradley Cooper",
    "Rewrite the Stars — Zac Efron & Zendaya",
    "Let Me Love You — Mario",
    "Speechless — Dan + Shay",
    "Die for You — The Weeknd",
    "I Choose You — Ryann Darling",
    "God Gave Me You — Blake Shelton",
    "More Than Words — Extreme",
    "Until I Found You — Stephen Sanchez",
    "Sweet Creature — Harry Styles",
    "Somebody to Love — Queen",
    "All I Want — Kodaline",
    "Love Someone — Lukas Graham",
    "Best Part — Daniel Caesar ft. H.E.R.",
    "In Case You Didn’t Know — Brett Young",
    "She Will Be Loved — Maroon 5",
    "No Air — Jordin Sparks ft. Chris Brown",
    "Come Away With Me — Norah Jones",
    "Just a Kiss — Lady A",
    "This I Promise You — *NSYNC",
    "Right Here Waiting — Richard Marx",
    "Time After Time — Cyndi Lauper",
    "Have I Told You Lately — Rod Stewart",
    "Only You — Yazoo",
    "You Make It Real — James Morrison",
    "Falling Like the Stars — James Arthur",
    "In My Veins — Andrew Belle",
    "Forever and Ever, Amen — Randy Travis",
    "I Cross My Heart — George Strait",
    "My Girl — The Temptations",
    "Kiss Me — Sixpence None the Richer",
    "Thinking of You — Katy Perry",
    "1+1 — Beyoncé",
    "Magic — Coldplay",
    "Enchanted — Taylor Swift",
    "This Town — Niall Horan",
    "You're Beautiful — James Blunt",
    "Angel — Jack Johnson",
    "Tenerife Sea — Ed Sheeran",
    "Photograph — Ed Sheeran",
    "Supermarket Flowers — Ed Sheeran",
    "Ocean Eyes — Billie Eilish",
    "Fallin’ — Alicia Keys",
    "Put It All on Me — Ed Sheeran ft. Ella Mai",
    "She — Elvis Costello",
    "You’re the Inspiration — Chicago",
    "Let’s Get It On — Marvin Gaye",
    "All You Need Is Love — The Beatles",
    "Come What May — Moulin Rouge Cast",
    "Make It To Me — Sam Smith",
    "Latch (Acoustic) — Sam Smith",
    "Lay Me Down — Sam Smith",
    "Love of My Life — Queen",
    "Is This Love — Bob Marley & The Wailers",
    "I Wanna Know — Joe",
    "Just the Two of Us — Bill Withers",
    "Baby I’m Yours — Arctic Monkeys",
    "Grow Old With Me — Tom Odell",
    "How Long Will I Love You — Ellie Goulding",
    "The One — Kodaline",
    "Beautiful in White — Shane Filan",
    "Turning Page — Sleeping At Last",
    "Falling Slowly — Glen Hansard & Markéta Irglová",
    "My Love — Westlife",
    "Tonight I Wanna Cry — Keith Urban",
    "Open Arms — Journey",
    "I Could Fall in Love — Selena",
    "When I Look at You — Miley Cyrus",
    "Yours — Russell Dickerson",
    "I Get to Love You — Ruelle",
    "You Are My Sunshine — Jasmine Thompson",
    "I Was Made for Loving You — Tori Kelly ft. Ed Sheeran",
    "First Day of My Life — Bright Eyes",
    "Love Me Tender — Elvis Presley",
    "Heaven — Bryan Adams",
    "Here and Now — Luther Vandross",
    "Always and Forever — Heatwave",
    "I Swear — All-4-One",
    "Unforgettable — Nat King Cole & Natalie Cole",
    "You’ll Be in My Heart — Phil Collins",
    "You Raise Me Up — Josh Groban",
    "Bubbly — Colbie Caillat",
    "Lucky — Jason Mraz & Colbie Caillat",
    "Marry You — Bruno Mars",
    "Treasure — Bruno Mars",
    "Just the Way You Are — Billy Joel",
    "Happy Together — The Turtles",
    "Crazy in Love — Beyoncé ft. Jay-Z",
    "I Knew I Loved You — Savage Garden",
    "Dreaming of You — Selena",
    "All For Love — Bryan Adams, Rod Stewart & Sting",
    "Love You Like a Love Song — Selena Gomez",
    "Love Me Like You — Little Mix",
    "Somebody — Dagny",
    "Count on Me — Bruno Mars",
    "She’s in Love With the Boy — Trisha Yearwood",
    "Dancing on My Own (Acoustic) — Calum Scott",
    "Me & You — HONNE",
    "I Do — Colbie Caillat",
    "Every Time We Touch — Cascada",
    "Love Song — Sara Bareilles",
    "You Belong With Me — Taylor Swift",
    "The Luckiest — Ben Folds",
    "Baby — Justin Bieber",
    "Better Together — Jack Johnson",
    "Still Falling for You — Ellie Goulding",
    "Sweetest Devotion — Adele",
    "Rolling in the Deep — Adele",
    "Let’s Fall in Love for the Night — FINNEAS",
    "Love You More — JLS",
    "Trampoline — SHAED",
    "All This Time — OneRepublic",
    "Ordinary People — John Legend",
    "Honeybee — The Head and the Heart",
    "Home — Edward Sharpe & The Magnetic Zeros",
    "Banana Pancakes — Jack Johnson",
    "Hold You in My Arms — Ray LaMontagne",
    "Beside You — James Blunt",
    "She’s Got a Way — Billy Joel",
    "Us — James Bay",
    "Make It Rain — Ed Sheeran",
    "Sweetest Thing — U2",
    "Shiver — Coldplay",
    "Tears Dry on Their Own — Amy Winehouse",
    "Come Rain or Come Shine — Ray Charles",
    "You Make Loving Fun — Fleetwood Mac",
    "Our Song — Taylor Swift",
    "Mine — Taylor Swift",
    "Sweet Nothing — Calvin Harris ft. Florence Welch",
    "Love Again — Dua Lipa",
    "Falling in Love at a Coffee Shop — Landon Pigg",
    "You're in My Heart — Rod Stewart",
    "All I Have — Jennifer Lopez ft. LL Cool J",
    "Like I’m Gonna Lose You — Meghan Trainor ft. John Legend",
    "H.O.L.Y. — Florida Georgia Line",
    "Invisible String — Taylor Swift",
    "Enchanted — Owl City",
    "Heaven — Kane Brown",
    "Forever After All — Luke Combs",
    "Heartbeat — Carrie Underwood",
    "Even If It Breaks Your Heart — Eli Young Band",
    "Into You — Ariana Grande",
    "Stuck with U — Ariana Grande & Justin Bieber",
    "Die With You — Beyoncé",
    "Love You Anymore — Michael Bublé",
    "Just the Same — Bruno Major"
]
}
